### ISSUE TITLE
Link to Autoload from the Readme is broken 404

### ISSUE THREAD

**Issue by estebanfeldman** [ValksGodotTools/GodotUtils#11]
The Link from the main repo page, hence the Readme, that links to the Autoload section is broken and gives 404

https://github.com/ValksGodotTools/GodotUtils/tree/main/Autoload

**Comment by valkyrienyanko** [comment]
Autoloads were removed from GodotUtils and moved to Template which you can find [here](https://github.com/ValksGodotTools/Template/tree/main/Scripts/Autoloads).

I've removed the link from the README in GodotUtils.

Thank you for telling me.
